version: '3'
services:
  go:
    container_name: algorithms_go
    build:
      context: ./docker/golang
    platform: linux/amd64
    volumes:
      - './:/go/algorithms'
    working_dir: '/go/algorithms'
    command: [ '/bin/sh', '-c', 'tail -f /dev/null' ]
    restart: always
